use_frameworks!

platform :ios, '11.0'

target 'XYPager_Example' do
  pod 'XYPager', :path => '../'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'

  target 'XYPager_Tests' do
    inherit! :search_paths

    
  end
end
